### ISSUE TITLE
Python 3 support and closed Google API

### ISSUE THREAD

**Issue by ProgVal** [ddan39/Supybot-IMDb#3]
I made a few changes to your plugin, mainly added Python 3 support and HTML scraping for Google instead of the public API that was closed yesterday.

You might want to merge some of them: https://github.com/ProgVal/Supybot-plugins/commits/master/IMDb

**Comment by ddan39** [comment]
Thanks, I will look at it soon.

**Comment by ddan39** [comment]
i added python 3 support long time ago, and have copied your code for using google plugin.
