### ISSUE TITLE
Google search 503 error

### ISSUE THREAD

**Issue by ddan39** [ddan39/Supybot-IMDb#5]
Looks like the google api I was using doesn't even work anymore... :(

will have to change it. ugh...

**Comment by ormanya** [comment]
It works for me from some IPs but not from others. Using an ssh proxy in my browser on these IPs, it seems that the IPs is not working for is ones where Google presents a captcha (e.g., my Digital Ocean droplet)

**Comment by ormanya** [comment]
One option is to use the DuckDuckGo plugin instead. Check out my fork of your plugin to see how I did it.

**Comment by ddan39** [comment]
yea i noticed it working again, and only rarely not working. will still get around to changing it soon though
